# Generated by Django 6.1.1 on 2026-09-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factors', '0001_initial'),
        ('market_data', '0001_initial'),
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('objective', models.CharField(max_length=40)),
                ('configuration', models.JSONField(default=dict)),
                ('holdings', models.JSONField(default=dict)),
                ('factor_exposures', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model_level', models.CharField(default='base_sector', max_length=24)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('configuration', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factor_build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_studies', to='factors.factorbuild')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_studies', to='selection.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('variant', models.CharField(default='standard', max_length=40)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('objective', models.CharField(default='min_variance', max_length=40)),
                ('expected_return_model', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('configuration', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('comparison', models.JSONField(default=dict)),
                ('expected_return', models.FloatField(blank=True, null=True)),
                ('expected_volatility', models.FloatField(blank=True, null=True)),
                ('factor_variance', models.FloatField(blank=True, null=True)),
                ('specific_variance', models.FloatField(blank=True, null=True)),
                ('turnover', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_scenarios', to='selection.portfolio')),
                ('screen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_scenarios', to='selection.screenrun')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='optimization.optimizationstudy')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_weight', models.FloatField(default=0)),
                ('equal_weight', models.FloatField(default=0)),
                ('optimized_weight', models.FloatField(blank=True, null=True)),
                ('expected_return', models.FloatField(blank=True, null=True)),
                ('marginal_risk', models.FloatField(blank=True, null=True)),
                ('component_risk', models.FloatField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market_data.security')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='optimization.optimizationscenario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scenario', 'security'), name='uq_optimization_holding')],
            },
        ),
    ]
