# Generated by Django 6.1.1 on 2026-09-07 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancel_requested', 'Cancellation requested'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('stage', models.CharField(blank=True, max_length=80)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=120)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('priority', models.SmallIntegerField(default=0)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'available_at', 'priority'], name='jobs_job_status_f0ee3c_idx')],
            },
        ),
    ]
