# Generated by Django 6.1.1 on 2026-09-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=60)),
                ('owner_type', models.CharField(max_length=60)),
                ('owner_id', models.PositiveBigIntegerField()),
                ('path', models.CharField(max_length=500)),
                ('format', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=80)),
                ('as_of', models.DateField()),
                ('universe', models.JSONField(default=list)),
                ('provenance', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFreeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('annualized_rate', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('asset_type', models.CharField(default='stock', max_length=32)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('exchange', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('current_shares', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('metadata_as_of', models.DateField(blank=True, null=True)),
                ('provenance', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('methodology', models.CharField(default='current_membership', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniverseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=120)),
                ('point_in_time', models.BooleanField(default=False)),
                ('survivorship_warning', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('provenance', models.JSONField(default=dict)),
                ('securities', models.ManyToManyField(related_name='universe_snapshots', to='market_data.security')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market_data.universe')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('as_of', models.DateField()),
                ('source', models.CharField(max_length=120)),
                ('checksum', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('missing_flags', models.JSONField(default=dict)),
                ('anomaly_flags', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('universe_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='market_data.universesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bars', to='market_data.security')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='market_data_date_2003ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'date'), name='uq_price_bar')],
            },
        ),
        migrations.AddConstraint(
            model_name='universesnapshot',
            constraint=models.UniqueConstraint(fields=('universe', 'as_of', 'source'), name='uq_universe_snapshot'),
        ),
    ]
