# Generated by Django 6.1.1 on 2026-09-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factors', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('configuration', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('screen', 'Screen'), ('optimized', 'Optimized')], default='manual', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.JSONField(default=dict)),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_portfolios', to='market_data.security')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('coverage', models.FloatField()),
                ('exposures', models.JSONField(default=dict)),
                ('active_exposures', models.JSONField(default=dict)),
                ('factor_variance', models.FloatField()),
                ('specific_variance', models.FloatField()),
                ('total_variance', models.FloatField()),
                ('predicted_volatility', models.FloatField()),
                ('realized_volatility', models.FloatField(blank=True, null=True)),
                ('tracking_error', models.FloatField(blank=True, null=True)),
                ('drawdown', models.FloatField(blank=True, null=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('component_risk', models.JSONField(default=dict)),
                ('marginal_risk', models.JSONField(default=dict)),
                ('attribution', models.JSONField(default=dict)),
                ('factor_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_risk', to='factors.factorbuild')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='selection.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('holdings', models.JSONField(default=dict)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='selection.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='RiskLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('metric', models.CharField(max_length=60)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factors.factordefinition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_limits', to='selection.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='BreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('observed_value', models.FloatField()),
                ('slack', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('risk_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='selection.portfoliorisksnapshot')),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='selection.risklimit')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('model_level', models.CharField(default='base_sector', max_length=24)),
                ('factor_weights', models.JSONField(default=dict)),
                ('directions', models.JSONField(default=dict)),
                ('regime_interactions', models.JSONField(default=dict)),
                ('filters', models.JSONField(default=dict)),
                ('top_n', models.PositiveSmallIntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='factors.factorbuild')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('status', models.CharField(default='pending', max_length=24)),
                ('diagnostics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='selection.screendefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('components', models.JSONField(default=dict)),
                ('rule_results', models.JSONField(default=dict)),
                ('model_fit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factors.stockmodelfit')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_results', to='market_data.security')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='selection.screenrun')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('shares', models.FloatField(blank=True, null=True)),
                ('cost_basis', models.FloatField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='selection.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to='market_data.security')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'security'), name='uq_portfolio_holding')],
            },
        ),
        migrations.AddConstraint(
            model_name='portfoliorisksnapshot',
            constraint=models.UniqueConstraint(fields=('portfolio', 'as_of'), name='uq_portfolio_risk_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('portfolio', 'as_of'), name='uq_portfolio_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='screenresult',
            constraint=models.UniqueConstraint(fields=('run', 'security'), name='uq_screen_result'),
        ),
    ]
