# Generated by Django 6.1.1 on 2026-09-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('model_version', models.CharField(default='FactorsToday-V2-Proxy-Thematic', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('completeness', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('unavailable', 'Unavailable')], default='partial', max_length=16)),
                ('expected_factor_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_factor_count', models.PositiveSmallIntegerField(default=0)),
                ('coverage', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FactorModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('config_version', models.CharField(blank=True, max_length=24)),
                ('configuration', models.JSONField(default=dict)),
                ('data_snapshot_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('metrics', models.JSONField(default=dict)),
                ('exposures', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FactorBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_version', models.CharField(default='FactorsToday-V2-Proxy-Thematic', max_length=40)),
                ('model_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_canonical', models.BooleanField(db_index=True, default=True)),
                ('mode', models.CharField(choices=[('replication', 'V2 proxy')], default='replication', max_length=20)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('as_of', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('coverage', models.JSONField(default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('input_checksum', models.CharField(blank=True, max_length=64)),
                ('update_state', models.CharField(choices=[('idle', 'Idle'), ('updating', 'Updating'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('last_factor_update_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factor_builds', to='market_data.pricesnapshot')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_builds', to='factors.factorbuild')),
            ],
        ),
        migrations.CreateModel(
            name='FactorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('external_name', models.CharField(blank=True, max_length=120)),
                ('model_version', models.CharField(default='FactorsToday-V2-Proxy-Thematic', max_length=40)),
                ('family', models.CharField(max_length=32)),
                ('level', models.CharField(default='base', max_length=24)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('provenance_badge', models.CharField(choices=[('exact_etf', 'Exact ETF construction'), ('public_approximation', 'Public approximation'), ('unsupported', 'Unsupported')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict)),
                ('coverage_status', models.CharField(choices=[('available', 'Available'), ('partial', 'Partial'), ('unsupported', 'Unsupported')], default='available', max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'model_version'), name='uq_factor_definition_version')],
            },
        ),
        migrations.CreateModel(
            name='FactorEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equation', models.JSONField(default=dict)),
                ('basket_weights', models.JSONField(default=dict)),
                ('regression_betas', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equations', to='factors.factorbuild')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equations', to='factors.factordefinition')),
            ],
        ),
        migrations.CreateModel(
            name='FactorModelCatalogMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='factors.factormodelcatalog')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_memberships', to='factors.factordefinition')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='factormodelcatalog',
            name='factors',
            field=models.ManyToManyField(related_name='model_catalogs', through='factors.FactorModelCatalogMembership', to='factors.factordefinition'),
        ),
        migrations.CreateModel(
            name='FactorObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('raw_return', models.FloatField(null=True)),
                ('pure_return', models.FloatField(null=True)),
                ('scaled_return', models.FloatField(null=True)),
                ('cumulative_index', models.FloatField(null=True)),
                ('coverage', models.FloatField(default=1.0)),
                ('quality_flags', models.JSONField(default=list)),
                ('provenance', models.JSONField(default=dict)),
                ('horizons', models.JSONField(default=dict)),
                ('zscores', models.JSONField(default=dict)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='factors.factorbuild')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='factors.factordefinition')),
            ],
        ),
        migrations.CreateModel(
            name='StockModelFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('period', models.DateField()),
                ('is_provisional', models.BooleanField(default=False)),
                ('source_price_checksum', models.CharField(blank=True, max_length=64)),
                ('source_factor_checksum', models.CharField(blank=True, max_length=64)),
                ('model_level', models.CharField(max_length=24)),
                ('alpha', models.FloatField()),
                ('adjusted_r2', models.FloatField()),
                ('residual_volatility', models.FloatField()),
                ('active_factor_count', models.PositiveSmallIntegerField()),
                ('design_factor_count', models.PositiveSmallIntegerField(default=0)),
                ('observation_count', models.PositiveIntegerField()),
                ('coverage', models.FloatField()),
                ('inference_method', models.CharField(default='ElasticNetCV selection; conditional OLS/HAC', max_length=80)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_fits', to='factors.factorbuild')),
                ('model_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_fits', to='factors.factormodelcatalog')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_fits', to='market_data.security')),
            ],
        ),
        migrations.CreateModel(
            name='StockExposureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta', models.FloatField()),
                ('standard_error', models.FloatField()),
                ('t_stat', models.FloatField()),
                ('p_value', models.FloatField()),
                ('confidence_low', models.FloatField()),
                ('confidence_high', models.FloatField()),
                ('selected', models.BooleanField(default=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_exposures', to='factors.factordefinition')),
                ('model_fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='factors.stockmodelfit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='factorbuild',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical', True), models.Q(('model_fingerprint', ''), _negated=True)), fields=('model_fingerprint',), name='uq_canonical_factor_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='factorequation',
            constraint=models.UniqueConstraint(fields=('build', 'factor', 'date'), name='uq_factor_equation'),
        ),
        migrations.AddConstraint(
            model_name='factormodelcatalogmembership',
            constraint=models.UniqueConstraint(fields=('catalog', 'factor'), name='uq_factor_model_catalog_member'),
        ),
        migrations.AddConstraint(
            model_name='factormodelcatalogmembership',
            constraint=models.UniqueConstraint(fields=('catalog', 'position'), name='uq_factor_model_catalog_position'),
        ),
        migrations.AddConstraint(
            model_name='factormodelcatalog',
            constraint=models.UniqueConstraint(fields=('slug', 'model_version'), name='uq_factor_model_catalog_version'),
        ),
        migrations.AddIndex(
            model_name='factorobservation',
            index=models.Index(fields=['factor', 'date'], name='factors_fac_factor__758725_idx'),
        ),
        migrations.AddConstraint(
            model_name='factorobservation',
            constraint=models.UniqueConstraint(fields=('build', 'factor', 'date'), name='uq_factor_observation'),
        ),
        migrations.AddConstraint(
            model_name='stockmodelfit',
            constraint=models.UniqueConstraint(fields=('build', 'security', 'period', 'model_level'), name='uq_stock_model_fit_period'),
        ),
        migrations.AddConstraint(
            model_name='stockexposuresnapshot',
            constraint=models.UniqueConstraint(fields=('model_fit', 'factor'), name='uq_stock_factor_exposure'),
        ),
    ]
