# Generated by Django 6.1.1 on 2026-09-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optimization', '0001_initial'),
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('configuration', models.JSONField(default=dict)),
                ('data_snapshot_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('metrics', models.JSONField(default=dict)),
                ('holdings', models.JSONField(default=list)),
                ('factor_exposures', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('result_path', models.CharField(blank=True, max_length=500)),
                ('lookback_months', models.PositiveSmallIntegerField(default=24)),
                ('methodology_version', models.CharField(default='FactorsToday-V2-Proxy-Thematic', max_length=40)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('optimization_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='optimization.optimizationscenario')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='selection.portfolio')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='selection.screendefinition')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=500)),
                ('format', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='backtests.backtestrun')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestRebalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField()),
                ('execution_date', models.DateField()),
                ('holdings', models.JSONField(default=dict)),
                ('equations', models.JSONField(default=dict)),
                ('exposures', models.JSONField(default=dict)),
                ('covariance', models.JSONField(default=dict)),
                ('optimizer', models.JSONField(default=dict)),
                ('risk', models.JSONField(default=dict)),
                ('costs', models.FloatField(default=0)),
                ('turnover', models.FloatField(default=0)),
                ('breaches', models.JSONField(default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalances', to='backtests.backtestrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'signal_date'), name='uq_backtest_rebalance')],
            },
        ),
    ]
